# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JOOQ Configuration
spring.jooq.sql-dialect=POSTGRES

# Secret key
jwt.secret-key=66556A586E3272357538782F4125442A472D4B6150645367566B597033733676

# Root logger level and log file location
logging.level.root=INFO
logging.file.name=app.log

# Level of logging for specific packages
logging.level.org.springframework.web=DEBUG
logging.level.com.yourcompany=TRACE

# Flyway Configuration
spring.flyway.url=jdbc:postgresql://localhost:5433/postgres
spring.flyway.user=postgres
spring.flyway.password=1234
spring.flyway.locations=classpath:db/migration

#aws
#aws.accessKey=AKIAQIJRRVRA42WC46UY
#aws.secretKey=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
#aws.region=eu-central-1
#aws.s3.bucketName=kaitech2024

aws.accessKey=AKIAQIJRRVRA42WC46UY
aws.secretKey=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
aws.region=eu-central-1
aws.s3.bucketName=kaitech2024
aws.bucket.url=https://kaitech2024.s3.eu-central-1.amazonaws.com/

#mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kaitechcrm@gmail.com
spring.mail.password=obzoqrsqinapcgoh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#File
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=100MB

#otp.api.url=https://api.mbank.kg/v1/otp/
#otp.api.authenticate=f9a6e1058e49dd221c1427dffef5731e7e3af57edac8c4ca74b23c35bbe0e0158db55e1b7631636c723dfed751e2a7c0551d1278beeaddfa0bfe986ca271b780
spring.jackson.serialization.indent-output=true
