# Database Configuration
spring.datasource.url=jdbc:postgresql://3.75.223.91:5432/postgres
spring.datasource.username=moreuser
spring.datasource.password=morepass
spring.datasource.driver-class-name=org.postgresql.Driver

# JOOQ Configuration
spring.jooq.sql-dialect=POSTGRES

# Secret key
jwt.secret-key=66556A586E3272357538782F4125442A472D4B6150645367566B597033733676

# Root logger level and log file location
logging.level.root=INFO
logging.file.name=app.log

# Level of logging for specific packages
logging.level.org.springframework.web=DEBUG
logging.level.com.yourcompany=TRACE

# Flyway Configuration
spring.flyway.url=jdbc:postgresql://3.75.223.91:5432/postgres
spring.flyway.user=moreuser
spring.flyway.password=morepass
spring.flyway.locations=classpath:db/migration


aws.accessKey=AKIARYEUCF5PZH2ISNXV
aws.secretKey=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
aws.region=eu-north-1
aws.s3.bucketName=moremancafe
aws.bucket.url=https://moremancafe.s3.eu-central-1.amazonaws.com/

#File
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=100MB


spring.jackson.serialization.indent-output=true
